version: '3'
services:
  app:
    ports:
      - 80:3000
    restart: always
    command:
      - /wait-for-migrate-db-container.sh
      - db
      - node app.js
  mail:
    restart: always
  db:
    restart: always
