version: '3'
services:
  app:
    ports:
      - 3000:3000
    links:
      - mail
    networks:
      - mail
    depends_on:
      - mail
  init_db:
    volumes:
      - .:/app
  mail:
    image: tophfr/mailcatcher
    ports:
      - 8025:80 # for the web UI
    networks:
      - mail
networks:
  mail:
    driver: bridge
