version: '3'
services:
  app:
    ports:
      - 80:3000
    restart: always
    command:
      - /wait-for-migrate-db-container.sh
      - db
      - node app.js
    environment:
      - PGPASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_USER
      - DB_NAME
      - DB_PASSWORD
      - DATASTORE=postgresql
      - REDIS_HOST=redis_db
      - REDIS_URL=redis://redis_db:6379
      - LOG_LEVEL=silly
      - PORT=3000
      - EMAIL_SYSTEM_ADDRESS
      - EMAIL_HOST
      - EMAIL_USER
      - EMAIL_PASS
      - EMAIL_PORT
      - SAILS_SECRET
  migrate_db:
    environment:
      - PGPASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
  init_db:
    environment:
      - PGPASSWORD=${DB_PASSWORD}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    links:
      - db
    depends_on:
      - db
      - migrate_db
  db:
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis_db:
    restart: always
